### ISSUE TITLE
Error on pip install: "Unable to pre-compile ops without torch installed.[...]"

### ISSUE THREAD

**Issue by kajuberdut** [Capsize-Games/aihandler#1]
## Steps:
1. `pip install aihandler`
2. Error:  "Unable to pre-compile ops without torch installed. Please install torch before attempting to pre-compile ops."

## Details:

This error is probably related to the upstream library deepspeed. I am not at all sure if it can be resolved by first installing a specific version of pytoch and/or CUDA and I will try to test that when I have time. For now, this is simply to indicate that pip installing from PyPi does not work for windows and perhaps a requirement to that effect should be added to the readme.

### Versions:
  OS: Windows 11
  Python: 3.10.10
  Pip: 23.0.1
  
### Full error:
``` bash
Collecting deepspeed==0.8.0
  Downloading deepspeed-0.8.0.tar.gz (749 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 749.9/749.9 kB 11.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\{username}\AppData\Local\Temp\pip-install-jnbm25_9\deepspeed_c832fdb53eb84903810c4699e283a272\setup.py", line 122, in <module>
          assert torch_available, "Unable to pre-compile ops without torch installed. Please install torch before attempting to pre-compile ops."
      AssertionError: Unable to pre-compile ops without torch installed. Please install torch before attempting to pre-compile ops.
      [WARNING] Unable to import torch, pre-compiling ops will be disabled. Please visit https://pytorch.org/ to see how to properly install torch on your system.
       [WARNING]  unable to import torch, please install it if you want to pre-compile any deepspeed ops.
      DS_BUILD_OPS=1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
Note: running inside a new venv for isolation

**Comment by kajuberdut** [comment]
Note, according to setup.py the only requirement is aihandler so I attempted to install that to confirm that it would be the only entry in requirements.txt. However, I am blocked by https://github.com/Capsize-Games/aihandler/issues/1 so I was not able to confirm if this works.

**Comment by w4ffl35** [comment]
Thanks for the report --  looking into this now

**Comment by w4ffl35** [comment]
ah - i see you're on windows - that's the issue. I need to modify requirements for windows. fixing now (this does work on ubuntu currently)

**Comment by kajuberdut** [comment]
> ah - i see you're on windows - that's the issue. I need to modify requirements for windows. fixing now (this does work on ubuntu currently) - i do have windows solutions, should take about an hour or so to get it fixed up as i need to test the installation

I figured this was a windows issue. Thanks for the quick response and thank you for open sourcing your tools, they seem pretty neat!
